"""Allow system administrators without company

Revision ID: 009f8f03ee75
Revises: a0dedcf7ad65
Create Date: 2026-09-17 02:25:00.933651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009f8f03ee75'
down_revision = 'a0dedcf7ad65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
