"""Add product reserved quantity

Revision ID: 253ef2c5ea54
Revises: d21070e64c48
Create Date: 2026-09-14 04:46:46.023835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253ef2c5ea54'
down_revision = 'd21070e64c48'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'reserved_quantity',
                sa.Numeric(14, 3),
                nullable=False,
                server_default=sa.text("0")
            )
        )

    # Remove the database-level default after existing rows
    # have been populated with 0.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column(
            'reserved_quantity',
            server_default=None
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('reserved_quantity')

    # ### end Alembic commands ###
