"""Add manufacturing and expiry dates to purchase items

Revision ID: 2e56236b51fb
Revises: ce6f6814e5d2
Create Date: 2026-09-09 21:07:15.452384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e56236b51fb'
down_revision = 'ce6f6814e5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturing_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('manufacturing_date')

    # ### end Alembic commands ###
