"""add notification assignments

Revision ID: 52ac35f97fb0
Revises: d48f60353b58
Create Date: 2026-09-25 22:42:17.893217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ac35f97fb0'
down_revision = 'd48f60353b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_category', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', 'notification_category', name='uq_notification_assignment')
    )
    with op.batch_alter_table('notification_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_assignments_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_assignments_notification_category'), ['notification_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_assignments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_assignments_notification_category'))
        batch_op.drop_index(batch_op.f('ix_notification_assignments_company_id'))

    op.drop_table('notification_assignments')
    # ### end Alembic commands ###
