"""Add company settings

Revision ID: 69ad1392f796
Revises: d6a3d59a78bb
Create Date: 2026-09-25 10:15:53.614420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ad1392f796'
down_revision = 'd6a3d59a78bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('currency_position', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('time_format', sa.String(length=10), nullable=False),
    sa.Column('week_starts', sa.String(length=10), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=False),
    sa.Column('purchase_prefix', sa.String(length=20), nullable=False),
    sa.Column('expense_prefix', sa.String(length=20), nullable=False),
    sa.Column('booking_prefix', sa.String(length=20), nullable=False),
    sa.Column('number_length', sa.Integer(), nullable=False),
    sa.Column('include_date', sa.Boolean(), nullable=False),
    sa.Column('number_reset', sa.String(length=20), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_settings')
    # ### end Alembic commands ###
