"""add purchase delivery and supplier reference fields

Revision ID: 709d4b0c25ea
Revises: 63289eaad1f8
Create Date: 2026-09-14 10:54:07.327700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709d4b0c25ea'
down_revision = '63289eaad1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('expected_delivery_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('expected_delivery_date')
        batch_op.drop_column('supplier_invoice_number')

    # ### end Alembic commands ###
