"""Add booking signatures

Revision ID: 90f7279392b3
Revises: c1036ce21af1
Create Date: 2026-09-13 03:28:26.083032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f7279392b3'
down_revision = 'c1036ce21af1'
branch_labels = None
depends_on = None


def upgrade():
    # Booking signature columns already exist in the database.
    # Do not add them again.

    # Add a named unique constraint to expenses.reference
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_expenses_reference',
            ['reference']
        )

    # Remove the existing unique constraint from payments.reference
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_payments_reference',
            type_='unique'
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_payments_reference'), ['reference'])

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('staff_signature_date')
        batch_op.drop_column('customer_signature_date')
        batch_op.drop_column('staff_signature')
        batch_op.drop_column('customer_signature')

    # ### end Alembic commands ###
