"""Move maintenance mode to system settings

Revision ID: a304ad5df976
Revises: c1634aaec335
Create Date: 2026-09-26 03:10:55.361402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a304ad5df976'
down_revision = 'c1634aaec335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('maintenance_mode')
        batch_op.drop_column('maintenance_message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_mode', sa.BOOLEAN(), nullable=False))

    op.drop_table('system_settings')
    # ### end Alembic commands ###
