"""Add company active status

Revision ID: c6c04300f56e
Revises: 009f8f03ee75
Create Date: 2026-09-17 03:57:52.416058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c04300f56e'
down_revision = '009f8f03ee75'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )

    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            server_default=None
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
