"""Add bank transfer payment details

Revision ID: ce6f6814e5d2
Revises: f6ab993ca423
Create Date: 2026-09-09 16:14:07.350966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6f6814e5d2'
down_revision = 'f6ab993ca423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('account_number')
        batch_op.drop_column('account_name')
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
