"""Add inventory settings

Revision ID: d48f60353b58
Revises: 69ad1392f796
Create Date: 2026-09-25 11:01:09.994753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48f60353b58'
down_revision = '69ad1392f796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_negative_stock', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('reserve_stock', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('low_stock_notifications', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('stock_adjustment_requires_note', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('stock_adjustment_requires_note')
        batch_op.drop_column('low_stock_notifications')
        batch_op.drop_column('reserve_stock')
        batch_op.drop_column('allow_negative_stock')

    # ### end Alembic commands ###
